import { useState, useEffect, useCallback } from 'react';
import { useApp } from '../AppContext';
import type { NcShare } from '../api';

function formatDate(ts: number | null | undefined): string {
  if (!ts) return '—';
  return new Date(ts * 1000).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function formatExpiry(exp: string | null): string {
  if (!exp) return 'No expiry';
  const d = new Date(exp);
  const diff = Math.ceil((d.getTime() - Date.now()) / 86400000);
  if (diff < 0) return 'Expired';
  if (diff === 0) return 'Expires today';
  return `Expires in ${diff} day${diff === 1 ? '' : 's'}`;
}

export default function SharedLinksPage() {
  const { health, addToast } = useApp();
  const [shares, setShares] = useState<NcShare[]>([]);
  const [loading, setLoading] = useState(false);
  const [copiedId, setCopiedId] = useState<number | null>(null);
  const [deleteConfirm, setDeleteConfirm] = useState<NcShare | null>(null);

  const isOnline = health?.status === 'online';

  const loadShares = useCallback(async () => {
    if (!isOnline) return;
    setLoading(true);
    try {
      const { listShares } = await import('../api');
      setShares(await listShares());
    } catch (err: any) {
      addToast(err.message || 'Failed to load shares', 'error');
    } finally {
      setLoading(false);
    }
  }, [isOnline, addToast]);

  useEffect(() => { loadShares(); }, [loadShares]);

  async function handleDelete(share: NcShare) {
    try {
      const { deleteShare } = await import('../api');
      await deleteShare(share.id);
      addToast('Share link disabled', 'success');
      setShares((s) => s.filter((x) => x.id !== share.id));
    } catch (err: any) {
      addToast(err.message || 'Failed to delete share', 'error');
    } finally {
      setDeleteConfirm(null);
    }
  }

  async function copyLink(url: string, id: number) {
    await navigator.clipboard.writeText(url);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
    addToast('Link copied', 'success');
  }

  function getFilename(share: NcShare): string {
    return share.file_target?.split('/').pop() || share.token || String(share.id);
  }

  function isExpired(share: NcShare): boolean {
    if (!share.expiration) return false;
    return new Date(share.expiration).getTime() < Date.now();
  }

  return (
    <div className="page-content">
      <div className="page-header" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div>
          <h2 className="page-title">Shared Links</h2>
          <p className="page-subtitle">
            Control who can access individual files — without sharing your account.
          </p>
        </div>
        <button className="btn btn-secondary btn-sm" onClick={loadShares} disabled={!isOnline || loading}>
          <svg width="12" height="12" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}><path strokeLinecap="round" strokeLinejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>
          Refresh
        </button>
      </div>

      {/* Explainer */}
      <div className="card card-sm" style={{ marginBottom: 20, background: 'var(--color-accent-bg)', border: '1px solid #bfdbfe' }}>
        <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
          <svg width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="var(--color-accent)" strokeWidth={2} style={{ marginTop: 2, flexShrink: 0 }}><path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>
          <div style={{ fontSize: 12.5, color: 'var(--color-accent)', lineHeight: 1.6 }}>
            Share individual files with anyone using a generated link. The recipient does not need a SecureCloud account.
            Links are generated by Nextcloud and can be disabled at any time.
          </div>
        </div>
      </div>

      {!isOnline ? (
        <div className="card" style={{ textAlign: 'center', padding: '40px 24px', border: '1px solid #fecaca', background: 'var(--color-error-bg)' }}>
          <div style={{ fontWeight: 700, fontSize: 15, color: '#991b1b', marginBottom: 6 }}>Server Offline</div>
          <div style={{ fontSize: 13, color: '#b91c1c' }}>Share links cannot be loaded while your server is offline.</div>
        </div>
      ) : loading ? (
        <div style={{ display: 'flex', justifyContent: 'center', padding: '40px 0' }}>
          <span className="spinner" />
        </div>
      ) : shares.length === 0 ? (
        <div className="empty-state">
          <div className="empty-state-icon">
            <svg width="22" height="22" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" /></svg>
          </div>
          <div className="empty-state-title">No active share links</div>
          <div className="empty-state-body">Go to My Files and click Share on any file to create a controlled share link.</div>
        </div>
      ) : (
        <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
          <table className="file-table">
            <thead>
              <tr>
                <th style={{ paddingLeft: 20 }}>File</th>
                <th>Created</th>
                <th>Expiry</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {shares.map((share) => {
                const expired = isExpired(share);
                return (
                  <tr key={share.id}>
                    <td style={{ paddingLeft: 20 }}>
                      <div style={{ fontWeight: 500, fontSize: 13 }}>{getFilename(share)}</div>
                      <div style={{ fontSize: 11, color: 'var(--color-text-3)', fontFamily: 'monospace', marginTop: 2 }}>
                        {share.token}
                      </div>
                    </td>
                    <td style={{ fontSize: 12, color: 'var(--color-text-3)' }}>
                      {formatDate(share.stime || share.share_time)}
                    </td>
                    <td style={{ fontSize: 12 }}>
                      <span style={{ color: expired ? 'var(--color-error)' : 'var(--color-text-2)' }}>
                        {formatExpiry(share.expiration)}
                      </span>
                    </td>
                    <td>
                      {expired
                        ? <span className="badge badge-red">Expired</span>
                        : <span className="badge badge-green">Active</span>}
                    </td>
                    <td>
                      <div style={{ display: 'flex', gap: 4 }}>
                        <button
                          className="btn btn-secondary btn-xs"
                          onClick={() => copyLink(share.url || `${window.location.origin}/s/${share.token}`, share.id)}
                        >
                          {copiedId === share.id ? '✓' : 'Copy'}
                        </button>
                        <button
                          className="btn btn-secondary btn-xs"
                          onClick={() => window.open(share.url, '_blank')}
                        >
                          Open
                        </button>
                        <button
                          className="btn btn-danger btn-xs"
                          onClick={() => setDeleteConfirm(share)}
                        >
                          Disable
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Delete confirm modal */}
      {deleteConfirm && (
        <div className="modal-overlay">
          <div className="modal" style={{ width: 380 }}>
            <div className="modal-header">
              <div className="modal-title">Disable Share Link</div>
              <button className="modal-close" onClick={() => setDeleteConfirm(null)}>✕</button>
            </div>
            <p style={{ fontSize: 13.5, color: 'var(--color-text-2)', lineHeight: 1.6 }}>
              This will permanently disable the share link for <strong>{getFilename(deleteConfirm)}</strong>.
              Anyone with the link will no longer be able to access the file.
            </p>
            <div className="modal-footer">
              <button className="btn btn-secondary btn-sm" onClick={() => setDeleteConfirm(null)}>Cancel</button>
              <button className="btn btn-danger btn-sm" onClick={() => handleDelete(deleteConfirm)}>
                Disable Link
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
